// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Crawl():Promise<string>;

export function GetCrawlResults():Promise<Array<backend.Crawl>>;

export function StartCrawl(arg1:string,arg2:string):Promise<void>;
