// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CancelFetch():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function SaveFile(arg1:Array<backend.Crawl>):Promise<void>;

export function StartCrawl(arg1:string,arg2:string):Promise<void>;
