name: Wails build

on:
  push:
    tags:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [{ name: HeadofMasterCEMO, platform: darwin/arm64, os: macos-latest }]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          nsis: false
          sign: false
      - name: Get version
        run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ env.version }}',
              sha: context.sha
            })
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "dist/bin/ dist/shell/compiled.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
